# 运行容器
version: "3"
services:
  svr:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - OSS_SECRET_KEY # 拿到系统环境变量（通过终端命令env可以查看到的都可以拿）
        - CDN_SECRET_KEY
        - PUBLIC_URL # 拿到项目的环境变量(.env定义)
    command: npm start
