version: "3"
services:
  reverse-proxy:
    image: nginx:alpine
    ports:
      - 80:80
    # 注意：静态资源部署在了镜像当中，你也可以把它仅作为服务而把静态资源移出
    volumes:
      - ./reverse-proxy:/usr/share/nginx/html
      # - ./reverse-proxy/nginx-expression.conf:/etc/nginx/conf.d/default.conf
      # - ./reverse-proxy/nginx-proxy-pass.conf:/etc/nginx/conf.d/default.conf
      - ./reverse-proxy/nginx-http-directives.conf:/etc/nginx/conf.d/default.conf
  api-server:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    command: npm start
