version: "3"

services:
  frontend:
    container_name: frontend-app
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 80:3000
    command: npm start
  backend:
    container_name: backend-app
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    command: npm start
